#version 450


layout (local_size_x = 256) in;

struct DrawCullData
{
	mat4 view;
	mat4 proj;
	float frustum[4]; // data for left/right/top/bottom frustum planes
	float pyramidWidth, pyramidHeight; // depth pyramid size in texels
	float znear, zfar, drawDist;
	uint drawCount;

	int occlusionEnabled;
	int distanceCullEnabled;
};

layout(push_constant) uniform  constants{   
   DrawCullData cullData;
};


struct ObjectData{
	mat4 model;
	vec4 spherebounds;
}; 

// Object data buffer.
layout(std140,set = 0, binding = 0) readonly buffer ObjectDataBuffer{   

	ObjectData objects[];
} objectDataBuffer;

layout(set = 1, binding = 0) uniform SceneData{   
    mat4 view;
	mat4 proj;
	mat4 viewproj;
	vec4 ambientColor;
	vec4 sunlightDirection; //w for sun power
	vec4 sunlightColor;
} sceneData;

struct DrawCommand
{
	uint    indexCount;
    uint    instanceCount;
    uint    firstIndex;
    int     vertexOffset;
    uint    firstInstance;
};

// Draw indirect buffer
layout(set = 2, binding = 0)  buffer DrawIndirectBuffer{   

	DrawCommand Draws[];
} drawIndirectBuffer;

struct InstanceIDs {
	uint objectID;
	uint batchID;
};

layout(set = 2, binding = 1) readonly buffer InstanceIDBuffer{   

	InstanceIDs Instances[];
} instanceIDBuffer;


layout(set = 2, binding = 2)  buffer FinalInstanceObjectIDBuffer{   

	uint IDs[];
} finalInstanceObjectIDBuffer;

layout(set = 2,binding = 3) uniform sampler2D depthPyramid;

bool frustumCull(vec3 center_view, float radius_world)
{
	bool visible = true;

	// Test if the minimum distance to left / right frustum plane is larger than -radius_world.
	visible = visible && center_view.z * cullData.frustum[1] - abs(center_view.x) * cullData.frustum[0] > -radius_world; 
	// Test if the minimum distance to upper / lower frustum plane is larger than -radius_world.
	visible = visible && center_view.z * cullData.frustum[3] - abs(center_view.y) * cullData.frustum[2] > -radius_world;

	// Test near / far frustum plane.
	float cameraSphereFarPos = center_view.z - radius_world;
	float cameraSphereNearPos  = center_view.z + radius_world;
	// Pos under view space is negative value, while znear and zfar is positive value.
	// So use -cameraSphereFarPos and -cameraSphereNearPos here.
	visible = visible && -cameraSphereFarPos > cullData.znear;
	visible = visible && -cameraSphereNearPos < cullData.zfar;

	if(cullData.distanceCullEnabled != 0)
	{
		visible = visible && -cameraSphereNearPos < cullData.drawDist; 
	}
	
	return visible;
}

// Use HZB depth pyramid to do occlusion cull.
bool occlusionCull(vec3 center_view, float radius_world, float znear, float zfar, mat4 proj, mat4 view, uint objectIndex)
{
	// Caculate LOD for sampling the depth pyramid.
	vec4 center_clip = proj * vec4(center_view,1.f);
	vec4 point_clip = proj * vec4(center_view + vec3(radius_world, 0.0f, 0.0f),1.f);

	vec3 center_ndc = center_clip.xyz / center_clip.w;
	vec3 point_ndc = point_clip.xyz / point_clip.w;

	float R_ndc = length(point_ndc - center_ndc);
	float texelCount = R_ndc * cullData.pyramidWidth;

	float texelThreshold = 5.0f; 
	if(texelCount <= texelThreshold){
		return true; // Skip small objects.
	} 

	float level = floor(log2(max(texelCount * 0.7f, 1.0f)));

	// Calculate the depth of the nearest point on the bounding sphere.
	float distC = length(center_view);
	vec3 nearestP = center_view * ((distC - radius_world) / distC);

	if(nearestP.z >= -znear - 1e-5)
	{
		return true; // Skip object that intersects with the near plane.
	}

	vec4 nearestP_clip = proj * vec4(nearestP, 1.0f);
	vec3 nearestP_ndc = nearestP_clip.xyz / nearestP_clip.w;
	vec2 uv = nearestP_ndc.xy * 0.5f + 0.5f;

	// Use depth in view space.
	int sampleCnt = 0;
	int sampleTarget = 1;
	vec3 samplePos_view[5];
	if(texelCount > 32.0f) sampleTarget = 3;
	if(texelCount > 64.0f) sampleTarget = 5;

	vec3 cameraRight   = vec3(view[0][0], view[1][0], view[2][0]);
	vec3 cameraUp      = vec3(view[0][1], view[1][1], view[2][1]);
	vec3 cameraForward = normalize(center_view);

	samplePos_view[sampleCnt++] = center_view - cameraForward * radius_world; 
	if(sampleTarget >= 2)
	{
		samplePos_view[sampleCnt++] = center_view + cameraRight * radius_world;;
		samplePos_view[sampleCnt++] = center_view - cameraRight * radius_world;
	}
	if(sampleTarget >= 6)
	{
		samplePos_view[sampleCnt++] = center_view + cameraUp * radius_world;
    	samplePos_view[sampleCnt++] = center_view - cameraUp * radius_world;
	}

	for (int i = 0; i < sampleTarget; i++) 
	{
		vec4 samplePos_clip = proj * vec4(samplePos_view[i], 1.0);
		vec3 samplePos_ndc = samplePos_clip.xyz / samplePos_clip.w;
		vec2 uv = samplePos_ndc.xy * 0.5 + 0.5;
		uv = clamp(uv, vec2(0.0), vec2(1.0));

		float depthTex_ndc = textureLod(depthPyramid, uv, level).x;
		float depthTex_view = -(znear * zfar) / (znear + depthTex_ndc * (zfar - znear));
		float pointDepth_view = samplePos_view[i].z;
		float depthBias = max(abs(pointDepth_view) * 0.002, 0.03) * (1.0 + level * 0.75);

		if (pointDepth_view >= depthTex_view - depthBias) {
			return true; // If any sample point is visible, then think this object is visible.
		}
	}

	return false;
}

bool IsVisible(uint objectIndex)
{
	vec4 sphereBounds = objectDataBuffer.objects[objectIndex].spherebounds;
	mat4 modelMat = objectDataBuffer.objects[objectIndex].model;

	// Culling is done under view space.
	vec3 center_view = (cullData.view * modelMat * vec4(sphereBounds.xyz,1.f)).xyz;
	float radius_world = sphereBounds.w;
	
	bool visible = true;

	// Frustum cull.
	visible = visible && frustumCull(center_view, radius_world);	

	// Occlusion cull.
	if(visible && cullData.occlusionEnabled != 0)
	{
		visible = visible && occlusionCull(center_view, radius_world, cullData.znear, cullData.zfar, cullData.proj, cullData.view, objectIndex);
	}

	return visible;
}

void main() 
{		
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		uint objectID = instanceIDBuffer.Instances[gID].objectID;
		bool visible = IsVisible(objectID);
		
		if(visible)
		{
			uint batchIndex = instanceIDBuffer.Instances[gID].batchID;
			uint countIndex = atomicAdd(drawIndirectBuffer.Draws[batchIndex].instanceCount,1);

			uint instanceIndex = drawIndirectBuffer.Draws[batchIndex].firstInstance + countIndex;

			finalInstanceObjectIDBuffer.IDs[instanceIndex] = objectID;
		}
	}
}