#version 450


layout (local_size_x = 256) in;

struct DrawCullData
{
	mat4 view;
	float P00, P11, znear, zfar, drawDist; // symmetric projection parameters
	float frustum[4]; // data for left/right/top/bottom frustum planes
	float lodBase, lodStep; // lod distance i = base * pow(step, i)
	float pyramidWidth, pyramidHeight; // depth pyramid size in texels

	uint drawCount;

	int occlusionEnabled;
	int distanceCullEnabled;
};

layout(push_constant) uniform  constants{   
   DrawCullData cullData;
};


struct ObjectData{
	mat4 model;
	vec4 spherebounds;
}; 

// Object data buffer.
layout(std140,set = 0, binding = 0) readonly buffer ObjectDataBuffer{   

	ObjectData objects[];
} objectDataBuffer;

struct DrawCommand
{
	uint    indexCount;
    uint    instanceCount;
    uint    firstIndex;
    int     vertexOffset;
    uint    firstInstance;
};

// Draw indirect buffer
layout(set = 0, binding = 1)  buffer DrawIndirectBuffer{   

	DrawCommand Draws[];
} drawIndirectBuffer;

struct InstanceIDs {
	uint objectID;
	uint batchID;
};

layout(set = 0, binding = 2) readonly buffer InstanceIDBuffer{   

	InstanceIDs Instances[];
} instanceIDBuffer;


layout(set = 0, binding = 3)  buffer FinalInstanceObjectIDBuffer{   

	uint IDs[];
} finalInstanceObjectIDBuffer;

layout(set = 0,binding = 4) uniform sampler2D depthPyramid;

layout(set = 0, binding = 5) uniform  SceneData{   
    mat4 view;
	mat4 proj;
	mat4 viewproj;
	vec4 ambientColor;
	vec4 sunlightDirection; //w for sun power
	vec4 sunlightColor;
} sceneData;


// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
bool projectSphere(vec3 C, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (C.z < r + znear)
		return false;

	vec2 cx = -C.xz;
	vec2 vx = vec2(sqrt(dot(cx, cx) - r * r), r);
	vec2 minx = mat2(vx.x, vx.y, -vx.y, vx.x) * cx;
	vec2 maxx = mat2(vx.x, -vx.y, vx.y, vx.x) * cx;

	vec2 cy = -C.yz;
	vec2 vy = vec2(sqrt(dot(cy, cy) - r * r), r);
	vec2 miny = mat2(vy.x, vy.y, -vy.y, vy.x) * cy;
	vec2 maxy = mat2(vy.x, -vy.y, vy.y, vy.x) * cy;

	aabb = vec4(minx.x / minx.y * P00, miny.x / miny.y * P11, maxx.x / maxx.y * P00, maxy.x / maxy.y * P11);
	aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f); // clip space -> uv space

	return true;
}


bool IsVisible(uint objectIndex)
{
	vec4 sphereBounds = objectDataBuffer.objects[objectIndex].spherebounds;
	mat4 modelMat = objectDataBuffer.objects[objectIndex].model;

	// Culling is done under view space.
	vec3 center = (cullData.view * modelMat * vec4(sphereBounds.xyz,1.f)).xyz;
	float radius = sphereBounds.w;
	
	bool visible = true;

	// Test if the minimum distance to left / right frustum plane is larger than -radius.
	visible = visible && center.z * cullData.frustum[1] - abs(center.x) * cullData.frustum[0] > -radius; 
	// Test if the minimum distance to upper / lower frustum plane is larger than -radius.
	visible = visible && center.z * cullData.frustum[3] - abs(center.y) * cullData.frustum[2] > -radius;

	// Test near / far frustum plane.
	float cameraSphereFarPos = center.z - radius;
	float cameraSphereNearPos  = center.z + radius;
	// Pos under view space is negative value, while znear and zfar is positive value.
	// So use -cameraSphereFarPos and -cameraSphereNearPos here.
	visible = visible && -cameraSphereFarPos > cullData.znear;
	visible = visible && -cameraSphereNearPos < cullData.zfar;

	if(cullData.distanceCullEnabled != 0)
	{
		visible = visible && -cameraSphereNearPos < cullData.drawDist; 
	}

	// Flip Y because we access depth texture that way
	center.y *= -1;

	// Use HZB depth pyramid to do occlusion cull.
	if(visible && cullData.occlusionEnabled != 0)
	{
		vec4 aabb;
		if (projectSphere(center, radius, cullData.znear, cullData.P00, cullData.P11, aabb))
		{
			float width = (aabb.z - aabb.x) * cullData.pyramidWidth;
			float height = (aabb.w - aabb.y) * cullData.pyramidHeight;

			float level = floor(log2(max(width, height)));

			// Sampler is set up to do min reduction, so this computes the minimum depth of a 2x2 texel quad
            float depth = textureLod(depthPyramid, (aabb.xy + aabb.zw) * 0.5, level).x;
			float depthSphere = cullData.znear / (center.z - radius);

			visible = visible && depthSphere >= depth;
		}
	}

	return visible;
}

void main() 
{		
	uint gID = gl_GlobalInvocationID.x;
	if(gID < cullData.drawCount)
	{
		uint objectID = instanceIDBuffer.Instances[gID].objectID;
		bool visible = IsVisible(objectID);
		
		if(visible)
		{
			uint batchIndex = instanceIDBuffer.Instances[gID].batchID;
			uint countIndex = atomicAdd(drawIndirectBuffer.Draws[batchIndex].instanceCount,1);

			uint instanceIndex = drawIndirectBuffer.Draws[batchIndex].firstInstance + countIndex;

			finalInstanceObjectIDBuffer.IDs[instanceIndex] = objectID;
		}
	}
}